apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceeyit-backend-monitor
  namespace: monitoring
  labels:
    app: ceeyit-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ceeyit-backend
  endpoints:
  - port: http
    interval: 30s
    path: /actuator/prometheus
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceeyit-frontend-monitor
  namespace: monitoring
  labels:
    app: ceeyit-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ceeyit-frontend
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
